version: '3'

services:
  manus-backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MANUS_CONFIG_PATH=/app/config/config.yaml
    restart: unless-stopped
